#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar  3 18:02:09 2026

@author: marta.navarrobernad
"""

import mne
import matplotlib.pyplot as plt
from pathlib import Path

GA_DIR = Path("/home/marta.navarrobernad/Desktop/sub-P02/eeg/GRAND_AVERAGES")
SPINAL_CH = ["Iz", "SC1", "S3", "S6", "SC6", "S14", "S18", "S7", "S11", "S15", "S19", "S5", "S9", "S13", "S17", "S4", "S8", "S12", "S16"]

def plot_ga(f_type="GABRIELI", ref="TH6"):
    file_path = GA_DIR / f"GA_{f_type}_{ref}-ave.fif"
    if not file_path.exists(): return

    ga = mne.read_evokeds(file_path, verbose=False)[0]
    ga.apply_baseline((-0.010, 0)) # Baseline visual final

    # Ventanas segun filtro
    tmin, tmax = (-0.015, 0.060) if f_type == "GABRIELI" else (-0.050, 0.500)
    ylim = (-5, 5) if f_type == "GABRIELI" else (-10, 10)

    plt.figure(figsize=(10, 6))
    ga_crop = ga.copy().crop(tmin, tmax)
    times = ga_crop.times * 1000
    
    # Canales espinales
    picks = [c for c in SPINAL_CH if c in ga.ch_names]
    data = ga_crop.copy().pick(picks).data * 1e6
    
    for i in range(data.shape[0]):
        plt.plot(times, data[i, :], color='gray', alpha=0.3, lw=0.8)
    
    plt.plot(times, data.mean(axis=0), color='red', lw=3, label='MEAN SPINAL')
    
    # Controles
    for ctrl in ["ENG_ERB", "ENG_AXILLA"]:
        if ctrl in ga.ch_names:
            plt.plot(times, ga_crop.copy().pick(ctrl).data[0]*1e6, lw=2, label=ctrl)

    plt.axvline(0, color='black', ls='--')
    plt.ylim(ylim)
    plt.title(f"GA {f_type} | Ref {ref} (n={ga.nave})")
    plt.legend()
    plt.show()

if __name__ == "__main__":
    plot_ga("GABRIELI", "TH6")
    plot_ga("WIMMER", "TH6")
